services:
  datamart:
    build:
      context: .
      dockerfile: images/datamart/Dockerfile
    ports:
      - "8000:8080"
    depends_on:
      db:
        condition: service_healthy
  proxy:
    build:
      context: images/proxy
      dockerfile: ./Dockerfile
    links:
      - "datamart:datamart_ip"
    ports:
      - "8001:80"
  db:
    env_file: ./env/.env
    image: mysql
    expose:
      - 3306
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
