apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-sample-linux-deployment-1
  namespace: eks-sample-app
  labels:
    app: eks-sample-linux-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eks-sample-linux-app
  template:
    metadata:
      labels:
        app: eks-sample-linux-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - name: nginx-1
          image: {{ .Values.ImageName }}
          ports:
            - name: http
              containerPort: 80
          imagePullPolicy: Always
      nodeSelector:
        kubernetes.io/os: linux
